FROM mysql:latest

# Environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=order_service
ENV MYSQL_USER=mysqlUser
ENV MYSQL_PASSWORD=mysqlPsswd

# Expose the default MySQL port
EXPOSE 3306

# Set the default command to run when the container starts
CMD ["mysqld"]



